### ISSUE TITLE
Oauth에 관한 제약사항

### ISSUE THREAD

**Issue by lsj8367** [Ark-inflearn/inflearn-clone-back#118]
# Oauth에 관한 제약사항

> **현재 Oauth관련 로그인 처리할 수 있는 서비스는 다음과 같습니다.**

- [x] **Google**
- [x] **Github**
- [x] **Facebook**
- [ ] **Kakao**
- [ ] **Apple**

## Google

이슈 없습니다.

## Github

깃허브 로그인은 `Redirect URI` 설정이 한개밖에 되질 않습니다. 

~~현재 운영서버 URI를 등록해두었기 때문에 로컬에서는 테스트가 힘들고 서버에 올려서 테스트 해야하는 불편함이 있습니다.~~

**2021/09/03 12:00 수정**

### 해결사항

따로 한가지만 되질 않아서 제 계정에서 Oauth App을 설정했더니 해결하였습니다.

이 부분은 넘어가주셔도 좋습니다.

## Facebook

페이스북 로그인 연동은 잘 됩니다.

하지만, 페이스북 로그인시 회원의 계정 상태에 따라 받을 수 있는 응답이 다릅니다.

페이스북에 핸드폰 번호로 가입한 사용자의 경우 이메일이 없기 때문에 Oauth 로그인 시 페이스북에서 우리 서버로 넘어오는 응답에 이메일이 null로 들어옵니다. 

따라서 이 때 별도의 회원가입 페이지로 리다이렉트 시킨 후, 그곳에서 이메일을 입력받아서 가입을 시켜주어야 합니다.

즉, `별도의 회원가입 페이지가 필요`합니다.

## Kakao

카카오는 **사업자 등록**을 해야되기 때문에 현재 문의를 넣어놓은 상황입니다.

추가적인 답변이 오지 않거나 해결되지 않는다면 카카오는 Oauth연동에서 배제해야 될 것 같습니다.

## Apple

애플은 Oauth 연동에서 마저도 돈이 필요합니다.

기본 개발자 등록 + 개인 개발자 등록을 별도로 해야되는데

개인 개발자 등록시 `연간 구독 $99 결제`를 해야합니다.

## 정리

기능 구현을 요청받은지 꽤 되었지만 이런 이슈들로 인해 진행이 더딘 상황입니다.

다 같을줄 알았던 Response값과 제약사항이 업체마다 약간씩 다르기 때문에 이슈로 등록합니다.

같이 고민해주시면 좋을 것 같습니다. 🤔

**Comment by shirohoo** [comment]
애플은 돈미새인가요? 레전드네 🤷‍♂️

**Comment by lsj8367** [comment]
이슈가 해결되어 닫겠습니다.
