### ISSUE TITLE
무중단 배포 : overwrite와 rollback

### ISSUE THREAD

**Issue by MinChul-Son** [Ark-inflearn/inflearn-clone-back#123]
현재 `deploy.sh`를 수정하여 무중단 배포를 구현하였습니다.

무중단 배포의 과정은 다음과 같습니다.
1. Green으로 사용될 포트와 Nginx의 연결해제 (추가적인 트래픽을 막음)
2. Time Out을 위해 30초간 대기
3. Green 포트의 프로세스 중지 및 배포
4. Green 포트와 Nginx 연결
5. Nginx Reload

-------------------------------

제 별도의 ec2에서 문제없이 동작하는 것을 확인하였고 제가 현재 고민 중인 부분은 다음과 같습니다.

## 1.
새로운 버전이 문제가 없을 때는 `overwrite.sh`이라는 쉘 스크립트를 통해 Blue 포트에도 신버전을 동일하게 배포하려합니다.
그 `overwrite.sh`은 저희 프로젝트 내부에 작성하는 것이 좋을까요? 아니면 프로젝트 외부에 작성하는 것이 좋을까요?

## 2.
새로운 버전에 문제가 있어 Green 포트를 이전 버전으로 rollback 해야하는 상황을 위해 `rollback.sh`를 작성하려고 합니다.
이를 위해선 이전 버전의 `jar`를 백업해두는 과정이 필요할 것 같은데 이 부분을 어떻게 해야할까요?

**Comment by shirohoo** [comment]
1. 일반적으로 쉘스크립트는 프로젝트 내부에 작성하지 않습니다. `deploy.sh` 같은 경우는 `aws codedeploy`를 사용하는데 그렇게 해야 한다는 제약조건때문에 프로젝트 내부에 작성한거에요.

2. 기존 jar를 제거하거나 덮어쓰기하지 않고, 임의의 위치로 리눅스 mv 명령어를 통해 옮긴 후 새로운 jar를 배포하는 식으로 하면 이전 버전을 백업할수 있을 것 같고, 백업해둔 jar를 실행하는 별도의 쉘 스크립트를 작성하면 될 것 같네요. 실제로 젠킨스에서도 비슷한 동작구조로 롤백을 시킵니다.
