### ISSUE TITLE
@Builder의 문제점과 수정 방향

### ISSUE THREAD

**Issue by MinChul-Son** [Ark-inflearn/inflearn-clone-back#16]
# 문제점
`무지성`의 무서움을 느꼈어요.

현재 저희가 클래스 레벨에 `@Builder`를 사용하다보니 추가로 모든 매개변수를 받는 생성자인 `@AllArgsConstructor`가 필요해요. 즉, 클래스 레벨의 `@Builder`는 모든 멤버 필드에 대한 매개변수를 허용하게되요. 

저희가 원하는 것은 user 엔티티 생성 시점에는 `name`, `email`, `password`, `isSubscribed`를 입력받고 그 외의 필드는 이후의 서비스를 통해 채워넣는 시스템이에요. 모든 매개변수를 허용하게되면 여기서부터 모순이 발생해요.

또 JPA에서는 컬렉션을 필드 초기화를 하는 것이 안전한데, `@Builder`는 모든 초기화를 무시하기 때문에 아래와 같은 `warning`이 발생해요. 이를 위해선 필드가 변경되지 않도록 `final`을 붙이거나 추후에 변경가능성이 있다면 `@Builder.Default`를 붙이라는 뜻이에요. 
```
warning: @Builder will ignore the initializing expression entirely. If you want the initializing expression to serve as default, add @Builder.Default. If it is not supposed to be settable during building, make the field final.
```
예를들어, 현재 저희의 코드에서는 `user`의 `lecture`를 필드 초기화를 하더라도 `@Builder.Default`가 없기 때문에 `lecture`는 `null`이 되요. 

그렇다고 `@Builder.Default`가 무조건 좋냐? 그건 또 아니에요. 이는 코드의 가독성을 떨어트려요.

사실, 클래스 레벨에 `@Builder`를 걍 쓰고 컬렉션을 필드초기화하지 않는다면 문제는 발생하지 않을꺼에요.
하지만 문제는 그 코드가 정말 `좋은 코드`일까? 라는 물음에는 `그렇지 않다`라고 생각해요.

#### 따라서 제가 수정하고 싶은 방향은 다음과 같아요.

------------------------------------------------

# 수정
빌더 패턴은 필드가 많은 클래스에 적용시키기 좋은 패턴이에요. 따라서 모든 클래스에 사용하는 것이 아닌 꼭 필요한 클래스에만 적용시키고 싶어요. 예를 들면, 필드가 많은 `lecture`가 해당될 것 같아요.

`video`와 같이 필드가 1~2개인 클래스는 굳이 빌더 패턴을 사용하지 않고 생성자를 사용하는거죠!

또한, `@Builder`를 클래스 레벨이 아닌 생성자 레벨에 달아 꼭 필요한 필드만 빌드 패턴을 적용시키고 싶어요.
이렇게 사용한다면 컬렉션의 필드 초기화와 빌드 패턴 두 가지를 동시에 잡을 수 있을 것 같아요.

**Comment by BananMoon** [comment]
오..어렵네요 
그럼 Lecture와 같은 필드가 많은 클래스는 필요한 필드에 대해서만 생성자 레벨에서 @Builder를 적용하고.
적은 필드의 video와 같은 클래스는 아예 적용하지 않는 걸로 이해하면 될까요?

그리고 Builder 패턴을 적용할 때는 @builder.Default를 붙이는 걸까요?

**Comment by MinChul-Son** [comment]
네 `Lecture`와 같은 클래스만 `@Builder`를 사용하고 `Video`와 같은 클래스는 우리가 흔히 사용하는 `생성자`를 사용하는 방향으로 생각 중이에요.

`@Builder`를 사용하더라도 `@Builder.Default`를 붙이지 않기 위해서 클래스 레벨이 아닌 생성자 레벨에 `@Builder`를 붙일 꺼에요.
그렇게 하면 `@Builder.Default`를 사용하지 않고도 컬렉션의 필드 초기화가 가능해지니까요!
