### ISSUE TITLE
[Feedback] 테이블 설계 / 엔티티 설계

### ISSUE THREAD

**Issue by MinChul-Son** [Ark-inflearn/inflearn-clone-back#3]
# 작업 내용
`백앤드 팀`에서 `DB 테이블` 설계와 실제 매핑될 `엔티티`에 대한 설계를 1차적으로 마쳤습니다.

## 테이블 설계
![erd](https://user-images.githubusercontent.com/60773356/128685024-692800c5-276d-4f88-8aa5-04bfadaf293e.PNG)

## 엔티티 설계
![entity](https://user-images.githubusercontent.com/60773356/128685067-5ea41ed1-c70a-4476-9f72-760d58a73190.PNG)

먼저 `핵심 도메인`에 관한 설계만 진행하고 `부수적인 도메인`에 대해서는 `점진적으로 확장`해나가는 방향으로 결정하였습니다.

# 피드백
저희가 설계한 내용을 보시고 궁금한 점이나 이상하다고 느끼시는 부분은 코멘트로 피드백 부탁드립니다.

또한 `lecture` 테이블의 `intro`칼럼은 강의의 소개글에 대한 내용입니다. 이 부분을 어떻게 해야할지에 대한 피드백도 부탁드립니다.

저희의 생각은 아래와 같습니다.
* 지식 공유자가 프론트쪽에서 소개글을 작성하고 `submit`을 한다.
* `정적 HTML파일` 또는 `HTML형식으로 된 코드` 자체가 문자 형식으로 DB에 저장된다.
* 추후에 학생이 이를 열람했을 때 DB에 있는 해당 `HTML파일` 또는 `HTML형식의 코드`가 프론트단으로 전달된다.
* 프론트 단에서 랜더링되어 화면에 출력된다.

이러한 과정을 생각하고 해당 칼럼을 만들었는데 이에 대한 피드백 부탁드립니다.

**Comment by TaehwanGo** [comment]
* Lecture 관련
- intro에 지금 강의 소개 글이 다 들어있는데 메인화면 보시면 카드형태로 뿌려진 곳에 마우스를 올리면 간단한 description이 있어요
그래서 이 부분을 따로 column으로 빼서 간단하게 소개하는 부분을 추가하면 좋을 것 같아요
- lecture에 cover image가 있어야 될 것 같아요 이 부분은 동영상을 업로드 할때 썸네일로 올리거나 자동으로 썸네일 추출을 한다면 그걸로 써도 될 것 같아요
- 평점이 저장되는 곳도 필요할 것 같아요
- 강의 난이도가 초급, 중급, 고급 이런식으로 구분이 되어있는데 이 부분도 추가 해야될 것 같아요
- 강의 마다 할인 기간과 퍼센트를 저장하는 곳도 필요할 것 같아요
- 독점 여부도 boolean으로 하나 저장 해야 될 것 같아요

* User 관련
- 저도 궁금한 점인데 가장 최근에 들었던 강의를 데이터를 저장했다가 주실 건지 생각해보시면 좋을 것 같아요

* 그 외
- 인프런 커뮤티 보시면 작성글이나 댓글 이런 것을 작성 하는 공간이 있는데 아직 급한건 아니지만 이 부분도 나중에 생각해보시면 좋을 것 같아요
- 메인화면 슬라이더가 있는데 그것도 DB에서 가져와야 될 것 같아요
아마 광고일 거 같은데 광고를 몇일 구매를 하면 구매일수 만큼 슬라이더에 띄워줘야 될 것 같아요
슬라이더 부분은 미팅때 같이 이야기 해봐도 좋을 것 같아요

**Comment by MinChul-Son** [comment]
> ## Lecture 관련
> * intro에 지금 강의 소개 글이 다 들어있는데 메인화면 보시면 카드형태로 뿌려진 곳에 마우스를 올리면 간단한 description이 있어요
>   그래서 이 부분을 따로 column으로 빼서 간단하게 소개하는 부분을 추가하면 좋을 것 같아요
> * lecture에 cover image가 있어야 될 것 같아요 이 부분은 동영상을 업로드 할때 썸네일로 올리거나 자동으로 썸네일 추출을 한다면 그걸로 써도 될 것 같아요
> * 평점이 저장되는 곳도 필요할 것 같아요
> * 강의 난이도가 초급, 중급, 고급 이런식으로 구분이 되어있는데 이 부분도 추가 해야될 것 같아요
> * 강의 마다 할인 기간과 퍼센트를 저장하는 곳도 필요할 것 같아요
> * 독점 여부도 boolean으로 하나 저장 해야 될 것 같아요
> 
> ## User 관련
> * 저도 궁금한 점인데 가장 최근에 들었던 강의를 데이터를 저장했다가 어떻게 주실 건지 생각해보시면 좋을 것 같아요
> 
> ## 그 외
> * 인프런 커뮤티 보시면 작성글이나 댓글 이런 것을 작성 하는 공간이 있는데 아직 급한건 아니지만 이 부분도 나중에 생각해보시면 좋을 것 같아요
> * 메인화면 슬라이더가 있는데 그것도 DB에서 가져와야 될 것 같아요
>   아마 광고일 거 같은데 광고를 몇일 구매를 하면 구매일수 만큼 슬라이더에 띄워줘야 될 것 같아요
>   슬라이더 부분은 미팅때 같이 이야기 해봐도 좋을 것 같아요

**Comment by MinChul-Son** [comment]
### 먼저 피드백 감사드립니다!! 😄😄
# Lecture 관련
* 간단한 `description` 부분은 제가 생각을 못했던 부분이네요 감사합니다. 어떤 의미인지 이해했습니다.
![image](https://user-images.githubusercontent.com/60773356/128700878-8e1c5c91-468c-4290-8ff2-03fb382b69c5.png)
* `lecture`의 `cover image`가 그림에서 표시한 부분이 맞다면 강의를 생성할 때 `cover image`를 강사가 등록하는 식으로 하는게 좋을 것 같습니다.
* 평점이 저장되는 곳은 제가 따로 만들지 않은 이유는 필요 없는 칼럼이라고 생각했기 때문입니다. `lecture` 엔티티를 보시면 `review` 엔티티와 양방향 연관 관계로 매핑되어 있습니다. 따라서 실제 `java 클래스`의 `lecture` 엔티티에는 `review` 엔티티를 담은 `List`가 포함될 것입니다. 따라서 `SQL의 그룹함수 AVG`를 사용해 `review.rating`의 평균값을 구해 출력해주는 방향으로 생각을 했습니다.
* 강의 난이도에 대한 부분도 생각하지 못한 부분이었습니다. 피드백 감사합니다.
* 강의의 할인에 대한 부분은 별도의 테이블을 만들고 `lecture`와` 1:1 양방향`으로 관계를 맺는 쪽으로 진행하겠습니다.
* 독점 여부는 어떤 의미를 뜻하는지요?

# User 관련
* 최근 강의부분은 `user`와 `1:1 단방향`으로 관계를 맺는 `last_view`라는 테이블을 만들어 칼럼으로 `last_lecture`와 `last_video`칼럼을 만듭니다.
* 학생이 특정 강의의 영상을 들으려고 했을 때 `last_view`테이블의 `last_lecture`에 강의의 id, `last_video`에 영상의 id가 들어갑니다.
* 로그인 한 유저가 메인 페이지에서 `최근 강의`를 클릭하면 이 때 `last_lecture`를 사용해 해당 강의의 `대쉬보드`로 이동합니다.
* `대쉬보드`에서 `이어 학습하기`를 클릭하면 `last_lecture`와 `last_video`을 사용해 해당 강의로 이동합니다.

제가 이 부분에서 실제 인프런 사이트를 확인해보니 위와 같은 방식으로 동작하고 있는 것 같습니다.
1. 로그인 후 메인 화면에서 `최근 강의` 클릭
![image](https://user-images.githubusercontent.com/60773356/128704127-70cc11ce-ab49-4cfb-a4aa-e02d3849c7fa.png)
* 마지막으로 본 강좌의 dashboard로 url 매핑

2.` 이어 학습하기`를 클릭
![image](https://user-images.githubusercontent.com/60773356/128704232-9214f2a2-2616-4424-8652-39e948708b75.png)
* 강의 + 영상 번호를 사용해 url 매핑


# 그 외
* 커뮤니티 부분은 윤지님과 이야기 당시 인지하고 있는 부분입니다. 핵심 도메인 개발 후 확장해가는 방향으로 진행하려 합니다.
* 슬라이더 부분은 별도의 테이블을 만들어 광고를 넣고 꺼내오는 식으로 하면 문제없을 것 같습니다. 이 부분도 일단 핵심 도메인 개발 이후에 확장해나가는 것이 어떨까요? 윤지님이 Spring이 익숙하신게 아니라서 저와 함께 개발을 진행하려면 강의 crud부터 천천히 확장해나가는 것이 좋을 것 같습니다.  

#### 추가적인 의견이나 피드백 있으시면 comment 부탁드립니다!!!🙂🙂

**Comment by TaehwanGo** [comment]
저도 독점이라는 태그가 무얼 의미하는지 잘 몰랐는데 제 생각엔 인프런에만 올라온 강의인지 아닌지를 의미하는 것 같아요
강의 리스트에 보면 독점이라는 태그가 붙어있는 강의가 있더라구요
백엔드 지금 너무 좋습니다.
천천히 진행하셔도 됩니다.
저도 회사업무에 부족한 공부도 해야되고 제가 그리고 배포까지 완전하게 프로세스를 잘 알고 있지 않아서 천천히 진행하셔도 문제없을 것 같습니다.
저희는 꾸준히하는게 제일 중요하다고 생각합니다.

**Comment by MinChul-Son** [comment]
좋다고 말씀해주시니 감사합니다 ㅎㅎ

추가적으로 다른 팀원분들 의견도 수용해서 초기 버전인 'version 1.0'로 확정하겠습니다.

버전은 도메인을 확장해나가면서 'version 1.5` `version 2.0`과 같이 업그레이드할 계획입니다.

**Comment by MinwooJJ** [comment]
제가 궁금했던 몇 가지를 토니님이 이미 더욱 자세히 말씀해주셨네요. 이거 한국이랑 여기랑 시간이 다르다보니 자꾸 중요한 시기를 놓치는 점이 아쉽네요. 
저도 백엔드는 모르는점이 많아서 혹시 다음 미팅때 다시 한 번 전체적으로 대화를 나눴으면 좋겠네요.
지금 진행하는 방향이나 방법은 저도 아주 만족합니다.

**Comment by MinChul-Son** [comment]
네 알겠습니다~ 이번 미팅 때 전체적인 방향에 대한 대화를 나누면 좋겠네요.
