### ISSUE TITLE
[ARK-5] GitHub Actions CI/CD 실패

### ISSUE THREAD

**Issue by shirohoo** [Ark-inflearn/inflearn-clone-back#51]
# ⚙ 문제점 [![ARK-5](https://badgen.net/badge/JIRA/ARK-5/0052CC)](https://jira.company.com/browse/ARK-5) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Ark-inflearn&utm_campaign=badge_info)

1. GitHub CI/CD 중 `@SpringBootTest`로 인해 `$user.home/team-ark-backend/database-information.properties`를 찾음
2. GitHub Actions은 GitHub의 클라우드 인스턴스에 도커 이미지를 풀어 동작하기 때문에 빌드 환경에서 위의 파일이 없음
3. `FileNotFoundException`이 발생하며 빌드가 실패함

---

임시로 `@SpringBootTest`를 제거하여 배포했습니다. 원인은 알겠는데 해결방안이 딱히 안떠오르네요.

**Comment by MinChul-Son** [comment]
흠... 어렵네요.. `DockerFile`을 만들어서 해당 `properties`파일을 도커 이미지에 집어넣을 수는 없을까요?

CI/CD 쪽이 거의 무지하니까 생각이 잘 안나네요 ㅠㅠ

**Comment by shirohoo** [comment]
> 흠... 어렵네요.. `DockerFile`을 만들어서 해당 `properties`파일을 도커 이미지에 집어넣을 수는 없을까요?
> 
> CI/CD 쪽이 거의 무지하니까 생각이 잘 안나네요 ㅠㅠ

그것도 생각을 해봤는데 우선 제가 도커를 쓸줄모릅니다. 😭

**Comment by shirohoo** [comment]
문제가 해결됐으므로 이슈를 닫습니다.
