### ISSUE TITLE
CORS 이슈

### ISSUE THREAD

**Issue by shirohoo** [Ark-inflearn/inflearn-clone-back#66]
아직 프론트 서버가 없습니다.

해서 우선 API 서버만 열어둔 상태로 프론트 팀은 각자 로컬에서 작업을 할 것 같아요.

이 경우 CORS 이슈가 생길 수 있습니다.

일단 CORS 이슈를 회피하기 위해 임시적으로 모든 요청에 대해 접근을 허용하는게 어떨까 싶어요.

**Comment by MinChul-Son** [comment]
그럼 `@CrossOrigin`을 적용해야겠네요 임시로.
저는 좋은 생각같습니다!

**Comment by shirohoo** [comment]
✔ `api/v1/**` 에 대해 임시로 CORS 정책을 허용
