### ISSUE TITLE
HttpSession에 관한 의견

### ISSUE THREAD

**Issue by lsj8367** [Ark-inflearn/inflearn-clone-back#87]
현재 Oauth2 인증 로그인 과정에서
`httpSession` 의 키 값은 임의로 `user` 로 할당해놓은 상태입니다.
![스크린샷 2021-08-29 오후 1 44 55](https://user-images.githubusercontent.com/74235102/131238739-0a8f648b-fb17-43c1-941a-e9a5ee58359a.png)

키값을 어떻게 해야할지 애매해서 이슈에 올립니다. 🤔

**Comment by shirohoo** [comment]
`Oauth20Authentication`  어때요?

**Comment by lsj8367** [comment]
Oauth2Authentication으로 해볼게요.

**Comment by lsj8367** [comment]
나중에 추가적으로 코멘트가 있다면 즉각 반영해볼게요.
의견 수렴해서 이슈 닫겠습니다.
